#!/bin/bash
openssl s_client -crlf -connect 74.125.206.108:993 -servername imap.gmail.com
#echo -en "\0login\0pass"|base64
iptables -t nat -A PREROUTING -i ppp0 -p tcp --dport 143 -j DNAT --to 192.168.69.2:20143
iptables -t filter -I FORWARD -d 192.168.69.2 -p tcp --dport 20143 -j ACCEPT

login via browser
https://support.google.com/mail/accounts/answer/78754

# use a router like MTM
iptables -t nat -I PREROUTING -i ppp0 -p tcp --dport 993 -j DNAT --to 173.194.69.108:993
iptables -t filter -I FORWARD -d 173.194.69.108 -p tcp --dport 993 -j ACCEPT
